import type { ParsedLogs } from "../../../../src/lib/contract";

/**
 * Live Zero.xyz log-parse capability.
 *
 * OWNED BY PERSON C — implemented on branch person-c-capabilities.
 * Until that branch merges, this stub throws and the caller in
 * clients.ts falls back to the local parser (parserSource: "fallback").
 * Person A: do not edit this file. Person C: this is the only file in
 * services/vigil-agent you may edit.
 */
export async function parseLogsLive(_raw: string): Promise<ParsedLogs> {
  throw new Error("zero-live: not implemented on this branch");
}
